# docker-compose.deploy.yml（部署环境覆盖配置）
# 因为https://docs.docker.com/compose/how-tos/multiple-compose-files/merge/#merging-rules
# 因为docker compose的合并规则，我们无法做到在dev里面覆盖prod的ports映射
# 所以只能维护两个独立的compose file了

# 目前只支持在mac，Linux，wsl2里面进行开发

name: eduagent-${USER}

# https://docs.docker.com/reference/compose-file/services/
services:
  eduagent-dev:
    # https://docs.docker.com/reference/compose-file/services/#build
    # https://docs.docker.com/reference/compose-file/build/
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        GROUP: ${GROUP}
    # The image field allows you to specify the name and tag of the image that will be built.
    image: eduagent:${USER}
    # only for test
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]
    hostname: eduagent-dev
    # 我懂了，这个东西会覆盖docker默认规则生成的名字，也就是projectname servicename
    # expose:
    #   - 8000
    # TODO: only for test, do not forget to remove this
    # ports:
    #   - "9536:8000"
    # just write this in the deploy script
    # ports:
    #   - "${TWITTER_SERVICE_PORT:-8000}:8000" # 通过环境变量动态配置端口, 默认为8000
    restart: unless-stopped
    volumes:
      - .:/home/${USER}/eduagent
      # 为什么需要git config？因为我们要在容器内部操作git
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - ~/.git-credentials:/home/${USER}/.git-credentials
    networks:
      eduagent-network: # ipv4_address: 172.16.0.8
    depends_on:
      - eduagent-db

  eduagent-api:
    image: eduagent:${USER}
    command: ["api"]
    hostname: eduagent-api
    expose:
      - 8000
    restart: unless-stopped
    volumes:
      - .:/home/${USER}/eduagent
      # - ~/.cache:/home/${USER}/.cache
    networks:
      eduagent-network:
    depends_on:
      - eduagent-dev

  eduagent-ui:
    image: eduagent:${USER}
    command: ["ui"]
    hostname: eduagent-ui
    # expose:
    #   - 8501
    ports:
      - "9537:8501"
    restart: unless-stopped
    volumes:
      - .:/home/${USER}/eduagent
      # - ~/.cache:/home/${USER}/.cache
    networks:
      eduagent-network: # ipv4_address:
    depends_on:
      - eduagent-dev
      - eduagent-db

  eduagent-db:
    image: postgres:17
    restart: unless-stopped
    hostname: eduagent-db
    # ports:
    #   - "5432:5432"
    expose:
      - 5432
    environment:
      # all set to default so you could just type
      # psql -h localhost to connent
      - POSTGRES_USER=ysu_keg
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=social_robot
    networks:
      - eduagent-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  eduagent-network:
