# HOW TO USE CONF FILE
# copy this file and rename to eduagent.toml, then modify it to use.

[project]
api_version = "v1"

[llm]
api_key = "NOKEY"
api_base = "https://open.bigmodel.cn/api/paas/v4/"
model_name = "glm-4.6"
embedding_model_name = "embedding-3"
temperature = 0.0

[database]
user = "ysu_keg"
password = "123456789"
host = "db.eduagent"
port = 5432
name = "eduagent"

[redis]
host = "redis.eduagent"
port = 6379
db = 0

[api]
secret_key = "a-very-secret-key-that-should-be-changed"

[service_auth]
secret_key = "change_me_service_secret"
issuer = "nextjs-service"
audience = "eduagent-api"
algorithm = "HS256"
leeway_seconds = 10

[milvus]
host = "eduagent-milvus"
port = 19530
collection = "eduagent_quiz_chunks"
dim = 1536
